package com.ismail.creatvt.passguard.helpers

import com.ismail.creatvt.passguard.R
import com.ismail.creatvt.passguard.model.Website

object WebsiteFactory {

    const val OTHER = "Other"

    private val iconsMap = mapOf(
        "amazon" to R.drawable.amazon,
        "facebook" to R.drawable.facebook,
        "twitter" to R.drawable.twitter,
        "twilio" to R.drawable.twilio,
        "twitch" to R.drawable.twitch,
        "github" to R.drawable.github,
        "gaana" to R.drawable.gaana,
        "google" to R.drawable.google,
        "instagram" to R.drawable.instagram,
        "snapchat" to R.drawable.snapchat,
        "bankofindia" to R.drawable.bankofindia,
        "hsbc" to R.drawable.hsbc,
        "hdfc" to R.drawable.hdfc,
        "sbi" to R.drawable.sbi,
        "ola" to R.drawable.ola,
        "oracle" to R.drawable.oracle,
        "skype" to R.drawable.skype,
        "slack" to R.drawable.slack,
        "soundcloud" to R.drawable.soundcloud,
        "spotify" to R.drawable.spotify,
        "stackoverflow" to R.drawable.stackoverflow,
        "swagger" to R.drawable.swagger,
        "zeplin" to R.drawable.zeplin,
        "telegram" to R.drawable.telegram,
        "wordpress" to R.drawable.wordpress,
        "yahoo" to R.drawable.yahoo,
        "linkedin" to R.drawable.linkedin,
        "ujjivan" to R.drawable.ujjivan,
        "punjab_national" to R.drawable.punjab_national,
        "icici" to R.drawable.icici,
        "idbi" to R.drawable.idbi,
        "epfo" to R.drawable.epfo,
        "kotak" to R.drawable.kotak,
        "yes_bank" to R.drawable.yes_bank,
        "axis_bank" to R.drawable.axis_bank,
        "central_bank" to R.drawable.central_bank,
        "citi_bank" to R.drawable.citi_bank,
        "union_bank" to R.drawable.union_bank,
        "netflix" to R.drawable.netflix,
        "reddit" to R.drawable.reddit,
        "ebay" to R.drawable.ebay,
        "apple" to R.drawable.apple,
        "discord" to R.drawable.discord,
        "dribbble" to R.drawable.dribbble,
        "whatsapp" to R.drawable.whatsapp,
        "microsoft" to R.drawable.microsoft,
        "adobe" to R.drawable.adobe,
        "tcs" to R.drawable.tcs,
        "leetcode" to R.drawable.leetcode,
        "hackerrank" to R.drawable.hackerrank,
        "quickheal" to R.drawable.quickheal,
        "upwork" to R.drawable.upwork,
        "godaddy" to R.drawable.godaddy,
        "heroku" to R.drawable.heroku,
        "scaler" to R.drawable.scaler,
        "freelancer" to R.drawable.freelancer,
    )

    fun getAllWebsites(): List<Website> = arrayListOf(
        Website("amazon", "Amazon", "other"),
        Website("facebook", "Facebook", "other"),
        Website("twitter", "Twitter", "other"),
        Website("twilio", "Twilio", "other"),
        Website("twitch", "Twitch", "other"),
        Website("github", "Github", "other"),
        Website("gaana", "Gaana", "other"),
        Website("google", "Google", "other"),
        Website("instagram", "Instagram", "other"),
        Website("snapchat", "Snapchat", "other"),
        Website("bankofindia", "Bank of India", "other"),
        Website("hsbc", "HSBC Bank", "other"),
        Website("hdfc", "HDFC Bank", "other"),
        Website("sbi", "State Bank of India", "other"),
        Website("ola", "OLA", "other"),
        Website("oracle", "Oracle", "other"),
        Website("skype", "Skype", "other"),
        Website("slack", "Slack", "other"),
        Website("soundcloud", "Soundcloud", "other"),
        Website("spotify", "Spotify", "other"),
        Website("stackoverflow", "Stackoverflow", "other"),
        Website("swagger", "Swagger", "other"),
        Website("zeplin", "Zeplin", "other"),
        Website("telegram", "Telegram", "other"),
        Website("wordpress", "Wordpress", "other"),
        Website("yahoo", "Yahoo", "other"),
        Website("linkedin", "Linkedin", "other"),
        Website("ujjivan", "Ujjivan Small Finance Bank", "other"),
        Website("punjab_national", "Punjab National Bank", "other"),
        Website("icici", "ICICI Bank", "other"),
        Website("idbi", "IDBI Bank", "other"),
        Website("epfo", "EPFO", "other"),
        Website("kotak", "Kotak Mahindra Bank", "other"),
        Website("yes_bank", "Yes Bank", "other"),
        Website("axis_bank", "Axis Bank", "other"),
        Website("central_bank", "Central Bank of India", "other"),
        Website("citi_bank", "Citi Bank", "other"),
        Website("union_bank", "Union Bank", "other"),
        Website("netflix", "Netflix", "other"),
        Website("reddit", "Reddit", "other"),
        Website("ebay", "eBay", "other"),
        Website("apple", "Apple", "other"),
        Website("discord", "Discord", "other"),
        Website("dribbble", "Dribbble", "other"),
        Website("whatsapp", "Whatsapp", "other"),
        Website("microsoft", "Microsoft", "other"),
        Website("adobe", "Adobe", "other"),
        Website("tcs", "Tcs", "other"),
        Website("leetcode", "LeetCode", "other"),
        Website("hackerrank", "HackerRank", "other"),
        Website("quickheal", "Quick Heal", "other"),
        Website("upwork", "Upwork", "other"),
        Website("godaddy", "GoDaddy", "other"),
        Website("heroku", "Heroku", "other"),
        Website("scaler", "Scaler", "other"),
        Website("freelancer", "Freelancer", "other"),
        Website("", OTHER, "other")
    ).sortedWith(Comparator { o1, o2 ->
        if(o1.name == OTHER) return@Comparator 1
        if(o2.name == OTHER) return@Comparator -1
        else o1.name.compareTo(o2.name)
    })

    fun getIcon(iconString: String): Int? {
        return iconsMap[iconString]
    }
}